[project]
name = "fastapi-starter"
version = "0.1.0"
description = "A light-weight fastapi starter"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.6",
]
