name: Release to Coding Registry

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Coding Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CODING_REGISTRY_ADDRESS }}
          username: ${{ secrets.CODING_REGISTRY_USERNAME }}
          password: ${{ secrets.CODING_REGISTRY_PASSWORD }}

      - name: Get image tag
        id: get_image_tag
        run: |
          GIT_TAG=${GITHUB_REF#refs\/tags\/}
          IMAGE_TAG=${GIT_TAG#}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_ENV"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: server/Dockerfile
          tags: "${{ secrets.CODING_REGISTRY_ADDRESS }}/public/app:${{ env.IMAGE_TAG }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
